FROM debian
ADD * /
RUN apt-get update
RUN apt-get -y install dnsmasq
RUN apt-get -y install python3
RUN echo 'conf-dir=/etc/dnsmasq.d/,*.conf' > /etc/dnsmasq.conf
RUN echo "user=root" >> /etc/dnsmasq.conf
EXPOSE 53 12345
CMD [ "python3" ,"/01_Server.py"]