FROM debian
ADD * ./
COPY libsodium-1.0.10.tar.gz ./libsodium-1.0.10.tar.gz

RUN apt-get update
RUN apt-get -y install python3 python3-distutils sudo git tar build-essential ssh aria2 screen ssh make gcc sudo vim wget curl proxychains locales

#install youtube-dl
RUN python3 get-pip.py
RUN pip3 install youtube-dl
RUN mkdir ~/.ssh/
RUN touch ~/.ssh/authorized_keys
#echo yourpublickey>>~/.ssh/authorized_keys
#install ssr
RUN chmod +x ./ssr
RUN mv ./ssr /usr/local/sbin/
RUN ssr install
#set config
COPY config.json /root/.local/share/shadowsocksr/config.json
COPY sshd_config /root/ssh/sshd_config
COPY proxychains.conf /etc/proxychains.conf
#build libsodium-1.0.10
RUN tar xzvf ./libsodium-1.0.10.tar.gz
RUN ./libsodium-1.0.10/configure
RUN make -j8 && make install
RUN echo /usr/local/lib > /etc/ld.so.conf.d/usr_local_lib.conf
RUN ldconfig
WORKDIR /root
EXPOSE 22
CMD ["python3","docker_server.py" ]
#CMD  service ssh start && tail -f /dev/null &