FROM debian
ADD * ./
COPY libsodium-1.0.10.tar.gz ./libsodium-1.0.10.tar.gz

RUN apt-get update
RUN apt-get -y install python3 rsync python3-distutils sudo git tar build-essential ssh aria2 screen ssh make gcc sudo vim wget curl proxychains locales

#install youtube-dl
RUN python3 get-pip.py
RUN pip3 install youtube-dl instagram-scraper
RUN mkdir ~/.ssh/
RUN touch ~/.ssh/authorized_keys
#echo yourpublickey>>~/.ssh/authorized_keys
#install ssr
RUN chmod +x ./ssr
RUN mv ./ssr /usr/local/sbin/
RUN ssr install
#set config
COPY config.json /root/.local/share/shadowsocksr/config.json
COPY sshd_config /root/ssh/sshd_config
COPY proxychains.conf /etc/proxychains.conf
#build libsodium-1.0.10
RUN tar xzvf ./libsodium-1.0.10.tar.gz
RUN ./libsodium-1.0.10/configure
RUN make -j8 && make install
RUN echo /usr/local/lib > /etc/ld.so.conf.d/usr_local_lib.conf
RUN ldconfig

#set for aria2
RUN mkdir ~/.aria2
RUN touch ~/.aria2/aria2.session
RUN touch ~/.aria2/aria2.log
RUN mv ./aria2.conf ~/.aria2/aria2.conf

VOLUME [ "/root/download" ]
WORKDIR /root
EXPOSE 22 80  7000-8030/udp 7000-8030/tcp 18184
CMD ["python3","/docker_server.py"]
