FROM debian
ADD * ./

RUN apt-get update
RUN apt-get -y install python3 python3-distutils sudo git tar build-essential ssh aria2 screen ssh make gcc sudo vim wget curl proxychains locales

#install youtube-dl
RUN python3 get-pip.py
RUN mkdir ~/.ssh/
RUN touch ~/.ssh/authorized_keys
WORKDIR /root
EXPOSE 22
CMD  service ssh start && tail -f /dev/null &