FROM python:3.7-slim
ADD redeem.py /
ADD requirements.txt /
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

VOLUME ["/root/redeemsystem", "/root/OperationLives"]
CMD [ "python" ,"/redeem.py"]
