FROM python:3.7-slim
ADD config_request.py /
ADD requirements.txt /
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

VOLUME ["/root/OperationLives"]
CMD [ "python" ,"/config_request.py"]
