FROM python:3.7-slim
ADD ftp_server.py /
ADD requirements.txt /
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

VOLUME ["/root/download_folder", "/root/download_folder"]
CMD [ "python" ,"/ftp_server.py"]
